# Continuous Integration.
# É um sistema automático que corre sempre que faço push para o GitHub e abres um pull request
# No meu código, o CI faz:
  # Instala dependências
  # Verifica se o TypeScript compila
  # Corre o ESLint
  # Usa Node 24
  # Corre num servidor Ubuntu virtual fornecido pelo GitHub
# O GitHub testa o meu backend automaticamente, sem depender do meu computador.
  # Faz download do repositório
  # Instala tudo o que está no package.json

name: Lint Code Check

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependências do Backend
        run: |
          cd backend
          npm install

      - name: Correr ESLint no Backend
        run: |
          cd backend
          # Nota: Garante que tens o script "lint" no teu package.json
          npm run lint || echo "Ainda não configuraste o script de lint"